---
sudo: required
language: python
services:
  - docker
matrix:
  include:
    - env: OPENDKIM_USE_CENTOS_BASE=true
install:
  - pip install molecule
  - pip install docker

branches:
  only:
    - master

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
